export const WORLD_LIMIT = 85;
export const SPAWN = { x: 0, z: 18 };
export const COLLIDERS = [
  { x: -18, z: -14, w: 12, d: 10 },
  { x: 23, z: 6, w: 10, d: 9 },
  { x: 29, z: -13, w: 9, d: 8 },
  { x: -32, z: 12, w: 9, d: 8 },
];
export const NPC = { x: -5, z: 13, name: "Master Hoshino" };
export const ENEMY_SPAWNS = [
  { id: "demon-1", x: -9, z: -4 },
  { id: "demon-2", x: 10, z: -8 },
  { id: "demon-3", x: -17, z: 7 },
  { id: "demon-4", x: 20, z: -24 },
  { id: "demon-5", x: -25, z: -26 },
  { id: "boss", x: 0, z: -43, boss: true },
];
export const STYLES = {
  water: {
    name: "Water",
    kanji: "水",
    color: "#6ddfff",
    glow: 0x56d9ff,
    description: "Flow like water. Strike like a tide.",
    abilities: [
      {
        name: "Water Wheel",
        short: "Wheel",
        cost: 20,
        cooldown: 5,
        damage: 38,
        range: 6,
        type: "spin",
      },
      {
        name: "Flowing Dance",
        short: "Flow",
        cost: 28,
        cooldown: 8,
        damage: 55,
        range: 12,
        type: "wave",
      },
      {
        name: "Dead Calm",
        short: "Calm",
        cost: 45,
        cooldown: 16,
        damage: 88,
        range: 9,
        type: "nova",
      },
    ],
  },
  flame: {
    name: "Flame",
    kanji: "炎",
    color: "#ff9b51",
    glow: 0xff763d,
    description: "An unwavering heart. An unyielding flame.",
    abilities: [
      {
        name: "Rising Sun",
        short: "Rise",
        cost: 20,
        cooldown: 5,
        damage: 44,
        range: 6,
        type: "slash",
      },
      {
        name: "Flame Tiger",
        short: "Tiger",
        cost: 30,
        cooldown: 9,
        damage: 65,
        range: 13,
        type: "wave",
      },
      {
        name: "Purgatory",
        short: "Blaze",
        cost: 48,
        cooldown: 17,
        damage: 110,
        range: 10,
        type: "nova",
      },
    ],
  },
  thunder: {
    name: "Thunder",
    kanji: "雷",
    color: "#ffe28a",
    glow: 0xffdc69,
    description: "One breath. One flash. One decisive strike.",
    abilities: [
      {
        name: "Thunderclap",
        short: "Flash",
        cost: 18,
        cooldown: 4,
        damage: 40,
        range: 10,
        type: "bolt",
      },
      {
        name: "Sixfold",
        short: "Sixfold",
        cost: 32,
        cooldown: 9,
        damage: 66,
        range: 14,
        type: "bolt",
      },
      {
        name: "Godspeed",
        short: "Speed",
        cost: 46,
        cooldown: 16,
        damage: 98,
        range: 16,
        type: "bolt",
      },
    ],
  },
  wind: {
    name: "Wind",
    kanji: "風",
    color: "#a6efbc",
    glow: 0x8aebad,
    description: "Cut through the silence with a gathering storm.",
    abilities: [
      {
        name: "Dust Whirlwind",
        short: "Whirl",
        cost: 20,
        cooldown: 5,
        damage: 36,
        range: 7,
        type: "spin",
      },
      {
        name: "Gale Slash",
        short: "Gale",
        cost: 28,
        cooldown: 8,
        damage: 54,
        range: 16,
        type: "wave",
      },
      {
        name: "Typhoon",
        short: "Storm",
        cost: 45,
        cooldown: 16,
        damage: 90,
        range: 12,
        type: "nova",
      },
    ],
  },
  mist: {
    name: "Mist",
    kanji: "霞",
    color: "#c5d6f7",
    glow: 0xbecfff,
    description: "Disappear into the haze. Return as the blade.",
    abilities: [
      {
        name: "Sea of Clouds",
        short: "Cloud",
        cost: 18,
        cooldown: 5,
        damage: 34,
        range: 8,
        type: "spin",
      },
      {
        name: "Shifting Flow",
        short: "Shift",
        cost: 28,
        cooldown: 8,
        damage: 56,
        range: 13,
        type: "wave",
      },
      {
        name: "Obscuring Clouds",
        short: "Veil",
        cost: 44,
        cooldown: 15,
        damage: 85,
        range: 11,
        type: "nova",
      },
    ],
  },
  sun: {
    name: "Sun",
    kanji: "日",
    color: "#ffce70",
    glow: 0xffc15e,
    description: "Carry the first light into the longest night.",
    abilities: [
      {
        name: "Solar Dance",
        short: "Dance",
        cost: 22,
        cooldown: 5,
        damage: 46,
        range: 6,
        type: "slash",
      },
      {
        name: "Burning Bones",
        short: "Burn",
        cost: 32,
        cooldown: 9,
        damage: 70,
        range: 12,
        type: "wave",
      },
      {
        name: "Sun Halo",
        short: "Halo",
        cost: 50,
        cooldown: 18,
        damage: 118,
        range: 11,
        type: "nova",
      },
    ],
  },
  moon: {
    name: "Moon",
    kanji: "月",
    color: "#d7acff",
    glow: 0xc699ff,
    description: "A thousand crescents beneath a silent sky.",
    abilities: [
      {
        name: "Dark Crescent",
        short: "Arc",
        cost: 20,
        cooldown: 5,
        damage: 40,
        range: 8,
        type: "slash",
      },
      {
        name: "Moonlit Cascade",
        short: "Fall",
        cost: 30,
        cooldown: 9,
        damage: 64,
        range: 14,
        type: "wave",
      },
      {
        name: "Lunar Eclipse",
        short: "Eclipse",
        cost: 48,
        cooldown: 17,
        damage: 105,
        range: 12,
        type: "nova",
      },
    ],
  },
  blood: {
    name: "Blood Art",
    kanji: "血",
    color: "#ff87a8",
    glow: 0xff467c,
    description: "Embrace the night. Awaken the power within.",
    abilities: [
      {
        name: "Blood Claws",
        short: "Claws",
        cost: 18,
        cooldown: 4,
        damage: 43,
        range: 6,
        type: "slash",
      },
      {
        name: "Crimson Thorns",
        short: "Thorns",
        cost: 28,
        cooldown: 8,
        damage: 58,
        range: 13,
        type: "wave",
      },
      {
        name: "Blood Moon",
        short: "Blood",
        cost: 45,
        cooldown: 16,
        damage: 98,
        range: 11,
        type: "nova",
      },
    ],
  },
};
export const TECHNIQUE_LEVELS = [1, 2, 3];
export function canOccupy(x, z, radius = 0.45) {
  if (Math.abs(x) > WORLD_LIMIT || Math.abs(z) > WORLD_LIMIT) return false;
  return !COLLIDERS.some(
    (c) =>
      Math.abs(x - c.x) < c.w / 2 + radius &&
      Math.abs(z - c.z) < c.d / 2 + radius,
  );
}
